Azure/azure-service-bus-node

lib/namespace.ts

Expose a mechanism for creating a subscription client.
/cc @amarzavery @ramya-rao-a

Expose a mechanism for creating a subscription client.

---

lib/namespace.ts

Add a method on the Namespace to format the DeadLetterPath for a queue.
Fixes #19

Add method to get the formatted path for the DeadLetterQueue

---

examples/topics/getRules.ts
examples/topics/receiveComplete.ts
examples/topics/simpleSend.ts
examples/topics/topicFilters.ts
lib/core/managementClient.ts
lib/index.ts
lib/subscriptionClient.ts
lib/util/constants.ts

This PR adds support to features listed in #12 i.e Topic Filters

Implement Topic Filters

---

samples/queuesGettingStarted.ts

Port the QueuesGettingStarted sample from the .NET sample.

Add sample for bus service for sending/receiving msgs in queue

---

examples/samples/queuesGettingStarted.ts

Move the queueGettingStarted to the examples\samples folder #56 
@AlexGhiondea @ramya-rao-a

Move the queueGettingStarted to the examples\samples folder

---

lib/session/messageSession.ts

At present a second receiveBatch() call on a session that is run after 60 seconds, fails with a "session already closed error" as the timer for "_newMessageReceivedTimer" doesnt get cleared after the first receiveBatch call succeeds.
Apart from the fix for the above, this PR has
- Cleanup of the `finalAction` method as we did in the batchingReceiver earlier 
- Remove the removeListener for `_onError` when receiveBatch completes. This was not required as `this._onError` was never added as a listener to the `ReceiverEvents.receiverError` event in the first place.
- Simplify `_createMessageSessionOptions()`
- Avoid adding to the messages array when it reaches max count.

Improvements to receiveBatch() in MessageSession

---

examples/msgRenewLock.ts
examples/peek.ts
examples/receiveAbandon.ts
examples/receiveAutoRenewLock.ts
examples/receiveBatch.ts
examples/receiveComplete.ts
examples/receiveDefer.ts
examples/receiveDeferredManagement.ts
examples/receiveWithoutAutoLockRenewAndComplete.ts
examples/samples/duplicateDetection.ts
examples/samples/receiveLoop.ts
examples/schedule.ts
examples/scheduleMultiple.ts
examples/session/getState.ts
examples/session/listSessions.ts
examples/session/peek.ts
examples/session/receiveComplete.ts
examples/session/receiveDeferredManagement.ts
examples/session/renewLock.ts
examples/session/setState.ts
examples/session/simpleSend.ts
examples/simpleSend.ts
examples/topics/getRules.ts
examples/topics/receiveComplete.ts
examples/topics/simpleSend.ts
examples/topics/topicFilters.ts

Formatting all the existing samples using the prettier
@AlexGhiondea @ramya-rao-a 
Fixes #72

Format all the existing samples using the prettier #72

---

examples/samples/SendersReceiversWithQueues.ts
examples/samples/autoForward.ts
lib/core/messageReceiver.ts
lib/session/messageSession.ts

Add the sample that retrieves from the queue using the receive handler.

Add SendersReceiversWithQueues and AutoForward sample

---

examples/samples/scheduledMessages.ts

Schedule messages to appear on Queue at a later time #62

Add ScheduledMessages sample

---

test/sendReceive.spec.ts

Adding some of the tests listed in #46

Tests for settling msgs using complete and abandon

---

.vscode/launch.json
README.md
test/README.md

This replaces https://github.com/Azure/azure-service-bus-node/pull/93

Add test instructions

---

lib/serviceBusMessage.ts

Fixing issue when user has not passed DeadLetterOptions in deadletter method.
Fixes #110

Deadletter fix

---

examples/samples/messageBrowse.ts

sendMessage() - sends a set of messages
peekMessage() - browse those messages 
receiveMessage() - receive the messages [ **To clear the queue** ]
Main difference from [ .NET Message Browse Sample](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.Azure.ServiceBus/MessageBrowse) is the addition of  **receiveMessage()** function to clear the flooded queue.

Added MessageBrowse sample

---

examples/samples/deferral.ts

Address linter errors in the sample

---

examples/samples/deferral.ts
examples/samples/messageBrowse.ts
examples/samples/topicFilters.ts
examples/samples/topicsGettingStarted.ts
lib/queueClient.ts
lib/serviceBusMessage.ts
lib/util/concurrentExpiringMap.ts

This sample demonstrates how to use advanced filters with ServiceBus topics and subscriptions. 
Fixes #67

Add topicFilter sample.

---

examples/samples/deferral.ts
examples/samples/session.ts
examples/samples/topicsGettingStarted.ts

* Added Session sample #65
* Resolved all the linter errors.
* Change topicGettingstarted sample(follow the same pattern as others).

Add Session sample and resolve linter errors.

---

test/batchReceiver.spec.ts
test/send.spec.ts
test/streamingReceiver.spec.ts

Related to #133
Refactoring the tests to different files

Refactor tests into different files 

---

examples/samples/README.md
examples/samples/topicsGettingStarted.ts

Recreating the PR on the right branch
https://github.com/Azure/azure-service-bus-node/pull/88 - Comments from @ramya-rao-a 
Will update the requested changes here.

Add README to execute the samples 

---

examples/samples/README.md

https://github.com/Azure/azure-service-bus-node/pull/108#issuecomment-451231180
@ramya-rao-a

Readme for the samples : final changes related to the .env file 

---

lib/serviceBusMessage.ts

Resolved : Deadletter related properties error.

---

package-lock.json

The bug #89 has been fixed in the upstream library rhea.
This PR pulls in the updates
- #89

Update dependencies for rhea #89

---

examples/samples/sessionState.ts
lib/session/messageSession.ts
test/README.md

Sample for session state using Shopping Cart scenario as discussed.
Includes bug fix for getState() to return the state and not void
- #64 
@AlexGhiondea @ramya-rao-a 
@ShivangiReja @HarshaNalluru

Implement sample for SessionState

---

lib/subscriptionClient.ts

Just like how we have session support in Queues, this PR copies over the same to subscriptions
- #94

Sessions for subscriptions #94

---

test/streamingReceiver.spec.ts

These don't involve calling receive for the second time(to clear the queue using receive) on the same queue/subscription.
Implemented tests for them and verified.
- With auto-complete enabled, manual deadletter in the Queue/Subscription by the user should not result in errors
- With auto-complete disabled, deferring a message results in not getting the same message again from queue/subscription. The message is then gotten using receiveDefferedMessages
- With auto-complete disabled, dead lettering the message results in not getting the same message again from queue/subscription. The message is then gotten only from the dead letter
- #101

Streaming Receiver Tests - Part 2

---

test/batchReceiver.spec.ts

Implement test for the second ReceiveBatch while the first one is not done.

Batch Receiver Test

---

lib/core/managementClient.ts
test/topicFilters.spec.ts

Allowing false filter as a part of Boolean filters
- Bug - https://github.com/Azure/azure-service-bus-node/issues/186
- #181 
- #153

Resolved false filter bug

---

README.md

This PR updates the README to include some text on the status of this SDK 
This helps in setting up expectations with our users

SDK status update

---

lib/core/managementClient.ts
test/topicFilters.spec.ts

**Action Bug of Topic Filters**
Updated the 'sql-rule-action' attribute of `ruleDescription`(changed the notation as per the [Docs](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-amqp-request-response#add-rule))
- #187

Action Bug of Topic Filters - Updated the 'sql-rule-action' attribute

---

test/receiveAndDeleteMode.spec.ts
test/streamingReceiver.spec.ts
test/topicFilters.spec.ts

Follow up to https://github.com/Azure/azure-service-bus-node/pull/215 to fix the chai.assert.fail() cases

Fix other test failures due to assert.fail

---

.vscode/launch.json
examples/README.md

Update readme for samples as per latest changes in samples: https://github.com/Azure/azure-service-bus-node/commit/a0343ea1dfa732e174d742c48e4286c549dc7df3

Update readme for samples as per latest changes in samples

---

test/streamingReceiver.spec.ts

- Updated `testDefer` in streamingReceiver to use `receiveDeferredMessages()` instead of `receiveDeferredMessage()` (#210). 
- dealing with multiple messages
- This works fine after the bug fix at #227
- #210 
- #227 
@ramya-rao-a

Updated testDefer in streamingReceiver to use receiveDeferredMessages

---

README.md

Update link to root repo for servicebus as a result of recent update to repo structure for servicebus

Update link to root repo for servicebus
