lib/queueClient.ts, lib/subscriptionClient.ts
Close the batching receiver in the queue client and the subscription client when the client is closed.
Fixes bug #25
=> Close the batching receiver on closing the client

lib/core/batchingReceiver.ts, lib/queueClient.ts, lib/subscriptionClient.ts
This PR address the issue #31 
- Updated `receiveBatch` call on the queueClient to re-use existing receiver if it is not currently receiving any messages
- Removed dead code from `finalAction()`.
When working on this, I realized that the initial `onReceiveMessage` handler which is used in the `_init()` call never gets disposed even after calling `this._receiver.removeListener(ReceiverEvents.message, onReceiveMessage);`
Due to this every call to `receiveBatch` will end up calling 2 instances of the `onReceiveMessage`.
@amarzavery Any thoughts on this?
=> Allow multiple recieveBatch calls on queueClient

lib/serviceBusMessage.ts
Implement a method that will return a sendable message from a received message.
This will enable re-sending of the same message to the queue.
Fixes #20
=> Add method for cloning a received message into a message that can be sent to the service

.vscode/settings.json, lib/core/managementClient.ts, lib/queueClient.ts, lib/session/messageSession.ts, package.json
- Update linting script in package.json, so that it runs as expected on non Windows machines
- Fix formatting errors in managementClient.ts file
- Fix the "Promise must be handled appropriately" errors in queueClient.ts and messageSession.ts
- `_ensureSessionLockRenewal` and `_resetTimerOnNewMessageReceived` need not be async. All they are doing is resetting timers
- Remove the formatOnPaste workspace setting, it doesnt work well with the prettier extension
=> Fix linting errors

lib/core/batchingReceiver.ts, lib/core/messageReceiver.ts
Since the `onReceiveMessage` of the batchingReciever gets the `.catch()` attached to it before being set as a handler on the receiver, the `removeListener` on it doesnt work which is important when we re-use the subsequent `receiveBatch` calls to work.
This PR covers
- move the try/catch to where the handlers are defined
- avoid passing defaults to `_createReceiverOptions()`
=> Ensure listeners are removed when receivers are re-used

lib/connectionContext.ts
Calling a `receive` or `receiveBatch` on a non existing namespace returns a non retryable error.
But, we continue to try to re-connect regardless.
This PR passes the connection related errors to the detached() call on the clients, so that the receivers are aware of the error and its non retryability.
=> Retry connecting only for retryable errors

examples/samples/deferral.ts
The send-side of the sample takes an ordered list of workflow steps (Shop, Unpack, Prepare, Cook, Eat) and puts them into the queue. The way we're shuffling these into a random order is by adding a random delay of a few milliseconds (30 ms) before each send operation. Sending is done when all send tasks are done.
What we're expecting for processing our workflow are instructions for 5 steps (Shop, Unpack, Prepare, Cook, Eat) to arrive, and we can only process them in order. We could start preparing the meal before we have shopped for extra ingredients we're missing, but the outcome might be disappointing.
Once we received a recipe step, we check whether it's the step we're expecting to process next. If that is the case, we handle it and complete the message. If the message arrives out of …
=> Add Deferral sample

lib/core/managementClient.ts, lib/util/constants.ts, package-lock.json, package.json
[Previously](https://github.com/Azure/azure-service-bus-node/commit/1b8dea568c1771d40398b59736fcf180127eed48#diff-5dea45ff6af62c0805b1e43f12ae0c64), we had added descriptorCodes for working with Topic Filters in the constants file. A better home for these is the `amqp-common` library. This PR updates our code to use these codes from the `amqp-common` library
=> Use descriptorCodes from amqp-common

lib/core/batchingReceiver.ts
Brief description of the changes made in the PR. This helps in making better changelog
- Remove `sessionError` listeners just like we remove the `message` and `receiverError` listeners
- Fix the issue of the `sessionError` event using the wrong listeners
- 
- https://github.com/Azure/azure-service-bus-node/issues/81
=> Remove sessionError listeners to avoid leak

lib/core/messageReceiver.ts, lib/core/messageSender.ts, lib/session/messageSession.ts
Brief description of the changes made in the PR. This helps in making better changelog
- Use `isItselfClosed()` instead of `isClosed()` to determine if the sdk has initiated the close
- Remove comment that indicated that we should attempt to reopen sender/receivers for retryable errors even when sdk has intiated the close()
- https://github.com/amqp/rhea/issues/170
cc @amarzavery
=> Use isItselfClosed() to determine if sdk initiatied close

lib/core/messageReceiver.ts
As described in https://github.com/Azure/azure-service-bus-node/issues/33, reconnecting the batching receiver link when the connection fails is not something we want to do
=> Skip reconnecting batching receiver when connection fails

lib/queueClient.ts, lib/util/concurrentExpiringMap.ts
-	When a deferred message is received, it is added to the requestResponseLockedMessages concurrent queue.
-	That concurrent map has a policy that will try to clean-up expired messages from the map. It does that by calling itself in a recursive function every 30 miliseconds or so.
-	Because the code keeps running, the sample does not exit.
/cc @amarzavery @ramya-rao-a
=> Make sure that we clear the map of deferred messages upon receiver closed

lib/core/batchingReceiver.ts, lib/session/messageSession.ts
When calling receiveBatch sequentially on the same client instance, there is a credit leak if the previous batch received fewer than maxMessageCount. batchingReceiver should be be setting the drain flow control flag as described in http://docs.oasis-open.org/amqp/core/v1.0/os/amqp-core-transport-v1.0-os.html#doc-flow-control in order to drain-off unused credits.
Brief description of the changes made in the PR:
- Added onReceiveDrain event handler. The handler unsubscribes the listener and resolves the promise with the received messages (if any).
- Changed finalAction to check remaining credits. If there any, it sets the drain flag on the link to cause the sender to drain the credits. At completion, the onReceiveDrain handler is called. If there are no remaning credits, finalAction …
=> Updating batchingReceiver to use drain to empty out credits.

lib/core/messageReceiver.ts
**Issue** - https://github.com/Azure/azure-service-bus-node/issues/145
**Steps to reproduce the behavior**
- Use a streaming receiver (by default autoComplete will be enabled)
- Complete the message in the onMessage callback (`await message.complete()`)
- The program takes more time to exit(about 20 seconds more) when added `await message.complete()` call in the onMessage callback.
**Observations**
- The actual workflow with `await message.complete()` call in the onMessage callback is 
- `complete() -> _onSettled() -> second complete()`.
- The reason for taking more time is [timer attribute of _deliveryDispositionMap(settimeout())]( https://github.com/Azure/azure-service-bus-node/blob/18f114dbfa0395b94de7380d8af9ceac26e8b560/lib/core/messageReceiver.ts#L781) is not getting cleared [Which …
=> Fixing the bug - Completing an already completed message

lib/session/messageSession.ts
messageSession.ts 
- Added check to know if the message is settled before calling the `complete()` method(coming from the `autoComplete` being true)
https://github.com/Azure/azure-service-bus-node/blob/fb7b77b5b9c6c67612ab69300d55c9dfc77abdb1/lib/session/messageSession.ts#L582
- https://github.com/Azure/azure-service-bus-node/issues/145
- https://github.com/Azure/azure-service-bus-node/pull/154
=> Fix AutoComplete Bug in messageSession.ts

test/batchReceiver.spec.ts
Implemented following tests for ReceiveBatch : 
1. No settling of the message results in getting the same message again (with delivery count incremented) from queue/subscription after the lock duration is expired.
2.   Ask for `n` msgs, but queue/subscription only has `m` msgs where m < n. This should return exactly `m` messages.
3.  Abandon/Deadletter/Defer a message received from recevieDefferedMessage using queue/subscription: 
-  Abandoning a message received from recevieDefferedMessage results in getting the same 
message again from queue/subscription using `receiveDefferedMessages`.
-  Deferring a message  received from recevieDefferedMessage results in not getting the same 
message again from queue/subscription. The message is then gotten using 
`receiveDefferedMessages`
- Dead …
=> Batch Receiver Tests

test/batchReceiver.spec.ts
We need to repeat all tests for queues as well as subscriptions.
Moreover we need to repeat them for paritioned and unparitioned variations of queues and subscriptions.
This PR refactors the tests to enable the above.
=> Refactor tests to reduce duplication of code

test/batchReceiver.spec.ts, test/streamingReceiver.spec.ts
Net changes in this PR:
- FIFO is not guaranteed unless we use sessions. Tests that expect `receivedMsgs` and `testMessages` to have contents in the same order are updated accordingly
- Tests are broken into separate logical chunks. This will help future maintaince
- Re-use test code between Queues and Subscriptions, autocomplete enable/disable
- Repeated code is moved to a common place
- Test descriptions updated to match the ones in the tests for the batching receiver
- Increased the time that we wait before stopping the receiveListener as it kept getting stopped before the messages were received.
- Add tests for abandon() when autoComplete is disabled
=> Refactoring StreamingReceiver Tests to re-use code across test cases

test/send.spec.ts
Brief description of the changes made in the PR. This helps in making better changelog
- Updated tests in `send.spec.ts` to be applied to un-partitioned queues and topics
- Added tests for cancelling scheduled messages
=> Tests for cancelScheduledMsg, and other send tests for unpartitioned entities

test/streamingReceiver.spec.ts
Second Streaming Receiver call - added a flag to check that it throws an error
Second Streaming Receiver call should fail if the first one is not stopped
> The test does check the error message in the catch() block. But this only guarantees that the error message is the expected one assuming that the error was indeed thrown. But there is nothing in the test that tests that the error indeed was thrown.
https://github.com/Azure/azure-service-bus-node/issues/101#issuecomment-454153613
- #101
=> Second Streaming Receiver call should fail if the first one is not stopped

lib/core/managementClient.ts
Both the [receiveDeferredMessages](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-amqp-request-response#deferred-message-operations) and [cancelScheduledMessages](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-amqp-request-response#cancel-scheduled-message) requests pass in the the array of sequence numbers in the request body.
This PR updates the `receiveDeferredMessages` call in this SDK to use the same code as `cancelScheduledMessages` for setting the sequence numbers in the message body.
This is part of the work to fix the issue described in #146
=> Use same code when sending sequencenumbers to rhea

lib/serviceBusMessage.ts, test/streamingReceiver.spec.ts
Implemented following test cases
1. Throws error when  complete/defer/abandon/deadletter already settled message.
2. User tries to settle messages received when in ReceiveAndDelete mode. In this case, the message is settled way before it even reaches the user.(Already covered this case in this issue #174)
=> Settle an already settled message test case.

examples/samples/scheduledMessages.ts, examples/schedule.ts, examples/scheduleMultiple.ts, lib/index.ts, lib/queueClient.ts, lib/topicClient.ts, test/send.spec.ts
Related to #173 
This PR updates the function signature for `scheduleMessage` and `scheduleMessages` to
- Use scheduleTime before the messages to be consistent with Go & Python SDK. This will also help in the future if we decide to use [rest parameters](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/rest_parameters)
- Update `scheduleMessages` to only support a single schedule time instead of separate ones for each message. 
- This makes the signature similar to that of `scheduleMessage`
- Avoids the user having to create a new object "ScheduleMessage"
- Makes feature consistent with Go & Python SDK
- Removes `ScheduleMessage` from index.ts as it is need not be exported and made visible to the user anymore
=> Simplify func signature for scheduling messages

test/send.spec.ts, test/testUtils.ts
This PR adds tests for the below scenarios for partitioned/unpartitioned queues/topics using sessions
- simple send
- schedule message
- schedule multiple messages
- cancel a scheduled message
- cancel multiple scheduled messages
=> Tests for Send using sessions

test/batchReceiver.spec.ts
Corrected the error messages(to be thrown when an entity is not empty) for sessions
- #195
=> Minor update - Batching Receiver Tests -  Error Messages

lib/session/messageSession.ts, test/maxDeliveryCount.spec.ts, test/streamingReceiver.spec.ts
This PR fixes 2 kinds of failing tests
- The ones in maxDeliveryCount.spec.ts were failing due to the `chai.assert.fail` that would fail all the time. Replaced this with a `should` check
- Updated receiveBatch() function in the messageSession.ts file to be async. This fixes the failures of "Throws error when ReceiveBatch is called while the previous call is not done" test cases for sessions as mentioned in https://github.com/Azure/azure-service-bus-node/pull/211#issuecomment-455451970
=> Fix failing tests

test/streamingReceiver.spec.ts
**Noticed some un-identified mistakes in the Streaming Receiver - Partitioned/Unpartitioned Tests**
In four test cases, unpartitioned entities are being passed as arguments in the place of partitioned entities.
In four test cases, partitioned entities are being passed as arguments in the place of unpartitioned entities.
- https://github.com/Azure/azure-service-bus-node/issues/191
=> Noticed some un-identified mistakes in the tests for Streaming Receiver

test/streamingReceiver.spec.ts
Testing DeliveryCount for `defer()` and `abandon()` in [`streamingReceiver.spec.ts`](https://github.com/Azure/azure-service-bus-node/blob/master/test/streamingReceiver.spec.ts)
- Tests corresponding to `defer()` didn't fail 
- Tests corresponding to `abandon()` fail sometimes.
- Observed `DeliveryCount` is not the same as expected `DeliveryCount`.
- **Cause** - Not being able to stop the `receiveListener` before the invocation of second `receive()`(This makes `DeliveryCount` equal to `2` instead of `1` ).
- https://github.com/Azure/azure-service-bus-node/issues/101#issuecomment-454153613
=> Testing DeliveryCount for defer() and abandon()

lib/subscriptionClient.ts
Found a bug related to `receiveDeferredMessages` module(in [subscriptionClient.ts](https://github.com/Azure/azure-service-bus-node/blob/master/lib/subscriptionClient.ts#L278)) while testing with streamingReceiver(#210).
```typescript
/**
* Receives a list of deferred messages identified by `sequenceNumbers`.
* @param sequenceNumbers A list containing the sequence numbers to receive.
* @returns Promise<ReceivedSBMessage[]>
* - Returns a list of messages identified by the given sequenceNumbers.
* - Returns an empty list if no messages are found.
* - Throws an error if the messages have not been deferred.
*/
async receiveDeferredMessages(sequenceNumbers: Long[]): Promise<ReceivedMessageInfo[]> {
if (this.receiveMode !== ReceiveMode.peekLock) {
throw new Error("The operation is only supported …
```
=> Receive deferred messages tests
